
import { RoadmapTrack } from './types';

export const iosRoadmap: RoadmapTrack = {
    id: 'ios',
    title: 'iOS Developer',
    description: 'Complete guide to becoming an iOS Developer in 2025',
    category: 'role-based',
    icon: '🍎',
    accentColor: '#007aff',
    rootNodeId: 'ios-root',
    nodes: {
        'ios-root': {
            id: 'ios-root',
            label: 'iOS Development',
            description: 'Build native iOS apps using Swift and SwiftUI.',
            children: ['ios-swift', 'ios-ui', 'ios-data', 'ios-publishing'],
            resources: [
                { type: 'documentation', title: 'Apple Developer Docs', url: 'https://developer.apple.com/documentation/', isFree: true },
                { type: 'video', title: 'CS193p Stanford SwiftUI Course', url: 'https://cs193p.sites.stanford.edu/', isFree: true },
                { type: 'course', title: 'iOS & Swift Bootcamp (Udemy)', url: 'https://www.udemy.com/course/ios-13-app-development-bootcamp/', isFree: false }
            ],
            content: {
                overview: 'iOS development means building apps for Apple\'s iPhone, iPad, Apple Watch, and Apple TV. Modern iOS development uses Swift as the programming language and SwiftUI as the declarative UI framework. Xcode is the required IDE (only available on macOS). The iOS ecosystem values user experience, performance, and adherence to Apple\'s Human Interface Guidelines. The App Store is the only distribution channel for consumer apps, with Apple reviewing every submission. iOS developers need to understand the Apple developer program, provisioning profiles, and code signing. The job market for iOS developers remains strong due to the high revenue generated by the App Store.',
                keyConcepts: [
                    'Swift programming language',
                    'SwiftUI for declarative UI',
                    'UIKit for legacy/complex UI needs',
                    'Xcode IDE and Instruments profiling',
                    'Apple Human Interface Guidelines (HIG)',
                    'App lifecycle: scene-based and SwiftUI App protocol',
                    'Core Data and SwiftData for persistence',
                    'App Store deployment and TestFlight'
                ],
                practiceQuestions: [
                    { question: 'Why is SwiftUI preferred over UIKit for new projects?', hint: 'SwiftUI is declarative (less code), has live previews, works across all Apple platforms, and is actively developed by Apple.', difficulty: 'easy' },
                    { question: 'Can you develop iOS apps on Windows?', hint: 'No. Xcode is macOS-only. You need a Mac for iOS development (or use a cloud Mac service).', difficulty: 'easy' }
                ],
                bestPractices: [
                    'Use SwiftUI for all new projects.',
                    'Follow Apple\'s Human Interface Guidelines for native look and feel.',
                    'Test on real devices, not just the simulator.',
                    'Join the Apple Developer Program early ($99/year for App Store publishing).',
                    'Use TestFlight for beta testing before App Store submission.'
                ]
            },
            dayWisePlan: [
                { day: 1, title: 'Swift Fundamentals', description: 'Learn the Swift language.', tasks: ['Variables, types, optionals, and control flow', 'Functions, closures, and protocols', 'Structs vs classes, enums with associated values'] },
                { day: 2, title: 'SwiftUI Basics', description: 'Build your first UI.', tasks: ['Create views with Text, Image, Button, VStack, HStack', 'Manage state with @State and @Binding', 'Build a simple list with NavigationStack'] },
                { day: 3, title: 'Data and Networking', description: 'Connect your app to data.', tasks: ['Fetch data from a REST API with URLSession', 'Parse JSON with Codable', 'Store data locally with SwiftData'] }
            ]
        },
        'ios-swift': {
            id: 'ios-swift',
            label: 'Swift Language',
            description: 'Master Swift: optionals, protocols, generics, closures, and concurrency.',
            parentId: 'ios-root',
            resources: [
                { type: 'documentation', title: 'The Swift Programming Language', url: 'https://docs.swift.org/swift-book/', isFree: true }
            ],
            content: {
                overview: 'Swift is a powerful, safe, and fast language designed by Apple. It was introduced in 2014 to replace Objective-C. Swift\'s type safety prevents common programming errors, optionals force explicit handling of nil values, and Automatic Reference Counting (ARC) manages memory without garbage collection. Protocols (similar to interfaces) define blueprints for functionality and are a core concept in Swift — Protocol-Oriented Programming (POP) is preferred over class inheritance. Swift\'s concurrency model (async/await, actors) provides structured, safe concurrent programming. Generics make code reusable across types.',
                keyConcepts: [
                    'Types: Int, String, Double, Bool, Array, Dictionary, Set',
                    'Optionals: String? for values that can be nil',
                    'Optional unwrapping: if let, guard let, nil coalescing (??)',
                    'Closures: inline functions, trailing closure syntax',
                    'Protocols and Protocol-Oriented Programming',
                    'Structs (value types) vs Classes (reference types)',
                    'Generics for reusable code',
                    'async/await and actors for concurrency'
                ],
                practiceQuestions: [
                    { question: 'When should you use a struct vs a class in Swift?', hint: 'Prefer structs (value types) for data models. Use classes when you need inheritance or reference semantics.', difficulty: 'medium' },
                    { question: 'What are optionals and why does Swift require them?', hint: 'Optionals represent a value that might be nil. They force you to handle the absence of a value, preventing crashes.', difficulty: 'easy' },
                    { question: 'What are actors in Swift?', hint: 'Reference types that protect their mutable state from data races by serializing access to their properties.', difficulty: 'hard' }
                ],
                bestPractices: [
                    'Use guard let for early exits instead of nested if let.',
                    'Prefer value types (structs) over reference types (classes).',
                    'Use Protocol-Oriented Programming over class inheritance.',
                    'Use async/await instead of completion handlers for async code.'
                ]
            }
        },
        'ios-ui': {
            id: 'ios-ui',
            label: 'SwiftUI',
            description: 'Build modern, declarative UIs with SwiftUI views, state management, and navigation.',
            parentId: 'ios-root',
            resources: [
                { type: 'documentation', title: 'SwiftUI Tutorials', url: 'https://developer.apple.com/tutorials/swiftui', isFree: true }
            ],
            content: {
                overview: 'SwiftUI is Apple\'s modern framework for building user interfaces across all Apple platforms with a single codebase. You describe your UI as a function of state — when state changes, SwiftUI automatically updates the view. @State wraps local view state, @Binding passes state to child views, @ObservableObject and @Published expose shared model state, and @EnvironmentObject provides dependency injection. NavigationStack manages hierarchical navigation. List efficiently displays scrollable content. The .modifier() syntax chains view modifiers for styling. SwiftUI previews in Xcode let you see changes instantly without running the app.',
                keyConcepts: [
                    'Views as structs: body computed property',
                    'View modifiers: .font, .padding, .background, .frame',
                    'Layout: VStack, HStack, ZStack, LazyVStack',
                    'State: @State, @Binding, @StateObject, @ObservedObject',
                    '@Observable macro (iOS 17+)',
                    'NavigationStack and NavigationLink',
                    'List and ForEach for collections',
                    'Animations: withAnimation, .transition, .animation'
                ],
                practiceQuestions: [
                    { question: 'What is the difference between @State and @Binding?', hint: '@State owns the data (source of truth). @Binding is a reference to state owned by a parent view.', difficulty: 'easy' },
                    { question: 'What is the @Observable macro?', hint: 'Introduced in iOS 17, it simplifies observable objects — no need for @Published or ObservableObject protocol.', difficulty: 'medium' }
                ],
                bestPractices: [
                    'Use @Observable (iOS 17+) instead of ObservableObject for new code.',
                    'Keep views small and extract subviews for readability.',
                    'Use previews extensively during development.',
                    'Follow the Human Interface Guidelines for native iOS feel.'
                ]
            }
        },
        'ios-data': {
            id: 'ios-data',
            label: 'Data & Networking',
            description: 'REST APIs, JSON parsing, SwiftData, Core Data, and local storage.',
            parentId: 'ios-root',
            resources: [
                { type: 'documentation', title: 'SwiftData', url: 'https://developer.apple.com/documentation/swiftdata', isFree: true }
            ],
            content: {
                overview: 'iOS apps need networking for API communication and local storage for offline data. URLSession is the built-in networking API for making HTTP requests. The Codable protocol makes JSON parsing simple — define your model struct conforming to Codable and use JSONDecoder. For third-party HTTP clients, Alamofire is popular. SwiftData (new in iOS 17) is the modern replacement for Core Data, providing a simpler API for local database persistence using Swift macros. UserDefaults stores small key-value pairs. Keychain securely stores sensitive data like tokens and passwords.',
                keyConcepts: [
                    'URLSession for HTTP requests',
                    'Codable protocol for JSON parsing',
                    'async/await with URLSession',
                    'SwiftData: @Model, @Query, ModelContainer',
                    'Core Data: entities, managed objects, fetch requests',
                    'UserDefaults for simple preferences',
                    'Keychain for secure storage (tokens, passwords)',
                    'Error handling for network failures'
                ],
                practiceQuestions: [
                    { question: 'What is the Codable protocol?', hint: 'A combination of Encodable and Decodable. It lets you convert Swift structs to/from JSON automatically.', difficulty: 'easy' },
                    { question: 'When should you use SwiftData vs UserDefaults?', hint: 'UserDefaults for simple settings (theme, language). SwiftData for structured data with relationships (like a to-do list).', difficulty: 'easy' }
                ],
                bestPractices: [
                    'Use async/await with URLSession instead of completion handlers.',
                    'Define Codable model structs that match your API response structure.',
                    'Use SwiftData for new projects instead of Core Data.',
                    'Store authentication tokens in Keychain, never in UserDefaults.'
                ]
            }
        },
        'ios-publishing': {
            id: 'ios-publishing',
            label: 'App Store Publishing',
            description: 'Code signing, TestFlight beta testing, App Store review, and distribution.',
            parentId: 'ios-root',
            resources: [
                { type: 'documentation', title: 'App Store Connect', url: 'https://developer.apple.com/app-store-connect/', isFree: true }
            ],
            content: {
                overview: 'Publishing an iOS app requires joining the Apple Developer Program ($99/year), configuring code signing (certificates and provisioning profiles), and submitting through App Store Connect. TestFlight lets you distribute beta versions to up to 10,000 testers before the official release. The App Store review process typically takes 24-48 hours — Apple reviews for crashes, privacy violations, content guidelines, and Human Interface Guidelines compliance. App Store Optimization (ASO) involves optimizing your app\'s title, keywords, screenshots, and description to improve discoverability.',
                keyConcepts: [
                    'Apple Developer Program enrollment',
                    'Certificates and provisioning profiles',
                    'App Store Connect: app management dashboard',
                    'TestFlight for beta distribution',
                    'App Store review guidelines',
                    'App Store Optimization (ASO)',
                    'In-app purchases and subscriptions (StoreKit)',
                    'Privacy: App Tracking Transparency, privacy labels'
                ],
                practiceQuestions: [
                    { question: 'What common reasons cause App Store rejection?', hint: 'Crashes, privacy violations, incomplete metadata, misleading descriptions, and violating design guidelines.', difficulty: 'medium' },
                    { question: 'What is TestFlight?', hint: 'Apple\'s beta testing platform that lets you distribute pre-release versions to testers before App Store release.', difficulty: 'easy' }
                ],
                bestPractices: [
                    'Test thoroughly on real devices before submission.',
                    'Write clear, honest app descriptions and screenshots.',
                    'Use TestFlight for beta testing with real users.',
                    'Add a privacy policy and complete all privacy labels.',
                    'Plan for App Store review time in your release schedule.'
                ]
            }
        }
    }
};
