"use client";

import { useSearchParams } from "next/navigation";
import { DashboardPage } from "@/components/dashboard/DashboardPage";
import CodeEditor from "@/components/ui/CodeEditor";
import { ArrowLeft, Sparkles, Building2 } from "lucide-react";
import { useRouter } from "next/navigation";

export default function ResumeTrackIDEPage() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const title = searchParams.get("title") || "Untitled Problem";
    const company = searchParams.get("company") || "Target Company";
    const pattern = searchParams.get("pattern") || "General";

    // Mock starter code based on pattern or generic
    const starterCode = {
        python: `# ${title} - ${company} Interview Question\n# Pattern: ${pattern}\n\nclass Solution:\n    def solve(self, input_data):\n        # Write your code here\n        pass`,
        javascript: `// ${title} - ${company} Interview Question\n// Pattern: ${pattern}\n\nfunction solve(input) {\n    // Write your code here\n    return null;\n}`,
        cpp: `// ${title} - ${company} Interview Question\n// Pattern: ${pattern}\n\n#include <iostream>\nusing namespace std;\n\nclass Solution {\npublic:\n    void solve() {\n        // Write your code here\n    }\n};`,
        java: `// ${title} - ${company} Interview Question\n// Pattern: ${pattern}\n\nclass Solution {\n    public void solve() {\n        // Write your code here\n    }\n}`
    };

    return (
        <DashboardPage>
            <div className="h-[calc(100vh-120px)] flex flex-col gap-4">
                <div className="flex items-center justify-between">
                    <button
                        onClick={() => router.back()}
                        className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors"
                    >
                        <ArrowLeft className="h-4 w-4" /> Back to Plan
                    </button>
                    <div className="flex items-center gap-3">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-500/10 text-orange-400 text-xs font-medium border border-orange-500/20">
                            <Building2 className="h-3 w-3" />
                            {company}
                        </div>
                        <h1 className="text-xl font-bold text-white max-w-xl truncate">{title}</h1>
                    </div>
                    <div className="w-24" /> {/* Spacer */}
                </div>

                <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-6 overflow-hidden">
                    {/* Problem Description Panel */}
                    <div className="bg-[#0a0a0a] rounded-2xl border border-white/10 p-6 overflow-y-auto">
                        <div className="flex items-center gap-2 text-orange-500 mb-4 font-bold text-sm">
                            <Sparkles className="h-4 w-4" /> AI Curated Question
                        </div>
                        <h2 className="text-2xl font-bold text-white mb-4">{title}</h2>
                        <div className="prose prose-invert max-w-none">
                            <p className="text-slate-300 mb-4">
                                This is a curated problem often asked in <strong>{company}</strong> interviews.
                                It relates to the <strong>{pattern}</strong> pattern identified as a focus area for you.
                            </p>

                            <h3 className="text-lg font-bold text-white mt-6 mb-2">Problem Statement</h3>
                            <p className="text-slate-400">
                                (Problem description would be generated by AI here. For now, assume standard problem constraints.)
                            </p>
                            <p className="text-slate-400 mt-2">
                                Given an input, return the simplified result adhering to the constraints.
                            </p>

                            <h3 className="text-lg font-bold text-white mt-6 mb-2">Example</h3>
                            <pre className="bg-black/50 p-3 rounded-lg text-sm font-mono text-slate-300">
                                Input: ...
                                Output: ...
                            </pre>
                        </div>
                    </div>

                    {/* Code Editor Panel */}
                    <div className="lg:col-span-2 h-full min-h-[500px]">
                        <CodeEditor
                            starterCode={starterCode}
                            functionName="solve"
                            // Mock test cases for now
                            testCases={[
                                { input: "test_input_1", output: "expected_output_1", hidden: false },
                                { input: "test_input_2", output: "expected_output_2", hidden: true }
                            ]}
                        />
                    </div>
                </div>
            </div>
        </DashboardPage>
    );
}
